#!/bin/sh

if [ ! -f "./INSTALL_PREFIX" ]; then
    echo "install prefix not defined! aborting!" 1>&2
    exit
fi

INSTALL_PREFIX="$(cat ./INSTALL_PREFIX)"

echo "-- deleting executables"
rm "$INSTALL_PREFIX/ser"
rm "$INSTALL_PREFIX/dm"

echo "-- done"
