#!/bin/sh

usage() {
    echo "USAGE: dm [-h, --help] [-a,--allow-non-text] [-o, --output-dir <DIR>] [SOURCE]"
}

OUTPUT_DIR=".out"
ONLY_TEXT=true
FILE_TO_SOURCE=""

while [ "$#" -gt 0 ]; do
    case $1 in
        -h | --help)
            usage
            exit
            ;;
        -a | --allow-non-text)
            ONLY_TEXT=false
            ;;
        -o | --output-dir)
            if [ ! "$2" = "" ]; then
                OUTPUT_DIR="$2"
                shift 2
            else
                echo "no output directory provided! aborting!" 1>&2
                exit
            fi
            ;;
        *)
            if [ "$FILE_TO_SOURCE" = "" ]; then
                FILE_TO_SOURCE="$1"
            else
                echo "invalid argument '$1'! aborting!" 1>%&2
                exit
            fi
            ;;
    esac
    shift
done

echo "output directory: $OUTPUT_DIR"
echo "disallow non-text files: $ONLY_TEXT"

if [ ! "$FILE_TO_SOURCE" = "" ]; then
    echo "sourcing file '$FILE_TO_SOURCE'"
    . "$FILE_TO_SOURCE"
fi

printf "is this directory [$(pwd)] correct? (y/N): "
read -r confirmation

case $confirmation in
    [yY][eE][sS]|[yY])
        echo "continuing"
        ;;
    *)
        echo "aborting!"
        exit
        ;;
esac

SER="ser"

echo "checking for 'ser'"
if [ "$(command -v ser)" = "" ]; then
    if [ -x "./ser" ]; then
        SER="./ser"
    else
        echo "'ser' not found! aborting!" 1>&2
        exit
    fi
fi
echo "found 'ser'"

if [ -d "$OUTPUT_DIR" ]; then
    echo "deleting previous output"
    rm -r "$OUTPUT_DIR"
fi

echo "deleting broken symlinks"
find -L ../ -type l -exec rm {} +

mkdir "$OUTPUT_DIR"

echo "duplicating directory tree"
for dir in */; do
    cp -a "$dir" "$OUTPUT_DIR"
done

for entry in $(find "$OUTPUT_DIR/"); do
    if [ -f "$entry" ]; then
        if file --mime-type "$entry" | grep -q "^.*: text/.*" || [ $ONLY_TEXT = false ]; then
            echo "generating '$entry'"
            printf "%s" "$($SER "$entry")" > "$entry"
        else
            echo "skipping '$entry'"
        fi
    fi
done

echo "symlinking generated files"
cp -rs "$(pwd)/$OUTPUT_DIR/" ../
